name: task_master_example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <4.0.0'

dependencies:
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4
  flutter:
    sdk: flutter
    
  intl: ^0.19.0
  cupertino_icons: ^1.0.2

  task_master:
    path: ../
  css:
    git:
      url: https://github.com/LimbitlessSolutionsInc/css.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    
